### ISSUE TITLE
no additional space after macro

### ISSUE THREAD

**Issue by OmegaDoom** [ned14/pcpp#29]
Hello.

For example we have following:
```
#define FUNC(rettype) rettype

FUNC(void)foo()
{
}

```

gcc -E output:

```
void foo()
{
}
```
pcpp output:
```
voidfoo()
{
}
```

**Comment by OmegaDoom** [comment]
microsoft preprocessor behaves like pcpp - [https://docs.microsoft.com/en-us/cpp/build/reference/e-preprocess-to-stdout?view=vs-2017](url)
Unfortunately i need gcc behavior. I preprocess a file where this issue is present and i cannot change the source.

**Comment by ned14** [comment]
An interesting corner case. I'll look into it, but it won't be until May.

**Comment by OmegaDoom** [comment]
Thank you!
An interesting article - [msvc-preprocessor-progress-towards-conformance](https://devblogs.microsoft.com/cppblog/msvc-preprocessor-progress-towards-conformance/)

**Comment by Sei-Lisa** [comment]
Wave also behaves like pcpp. The standard doesn't say anything about this, because according to it, the tokens output by the preprocessor are fed to the compiler with no text conversion in the middle. Standalone preprocessors that generate text output are not contemplated in the standard.

Arguably, however, a standalone preprocessor should ensure that parsing its output using a C compiler's tokenizer produces the same sequence of tokens that the compiler would take if they were integrated, and one obvious method is inserting whitespace between some tokens, as GCC does. IIRC this has ugly implications and corner cases that GCC does not cover.

**Comment by ned14** [comment]
Fixed in trunk, though I can see loads more corner cases that might now break in future :)
