### ISSUE TITLE
Token-pasting-related problem processing BOOST_WORKAROUND

### ISSUE THREAD

**Issue by joaquintides** [ned14/pcpp#42]
If I process the following with the `pcpp` command line tool:
```
#define BOOST_WORKAROUND(symbol, test)                \
       ((symbol ## _WORKAROUND_GUARD + 0 == 0) &&     \
       (symbol != 0) && (1 % (( (symbol test) ) + 1)))

#define BOOST_MSVC 1916
#define BOOST_MSVC_WORKAROUND_GUARD 0
BOOST_WORKAROUND(BOOST_MSVC,==1916)
```
the output is:
```
((1916_WORKAROUND_GUARD + 0 == 0) &&            (1916 != 0) && (1 % (( (1916 ==1916) ) + 1)))
```
while `g++ -E` produces:
```
((0 + 0 == 0) && (1916 != 0) && (1 % (( (1916 ==1916) ) + 1)))
```

**Comment by ned14** [comment]
Nice catch, thanks.

**Comment by ned14** [comment]
Finally got to fixing this, mainly due to me being sick of writing WG21 normative wording and I really, really wanted a break. pcpp now has a proper yacc based expression evaluator so complex `#if` expressions will now work properly. Apart from occasional whitespace differences, the edition in trunk ought to be much more capable of parsing most of Boost than before. Thanks for reporting this bug.

**Comment by joaquintides** [comment]
Thanks for fixing this! Best regards,
